sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qq2210630951
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tP9ffB3x7ctXiMYFPwZ
    access-key-secret: zXX69jQUPiCUFVa2PC1SIJ8tmBzMjA
    bucket-name: sky-take-out103
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx2b71086b0730f7e9 #小程序生成的唯一标识appid
    secret: 59c15bd79c78ab911ddeb5a9091c9f1c #小程序生成的秘钥